name = 'win7-aspnet4-sql_1.0.0';
vm_id = /"#{name}".*?\{(.*?)\}/.match(`VBoxManage list vms`)
vagrant_folder = './.vagrant/machines/default/virtualbox/';
if vm_id != nil && vm_id[1] != nil && !File.exist?("#{vagrant_folder}id")
  require 'fileutils'
  FileUtils::mkdir_p vagrant_folder
  config = File.new("#{vagrant_folder}id", 'w')
  config.puts(vm_id[1])
  config.close
end

Vagrant.configure(2) do |config|
  config.vm.box = name
  config.vm.box_url = "http://dev.fbiz.com.br/vm/#{name}.box"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"

  config.ssh.port = "2020"
  config.ssh.shell = ""

  config.vm.provider "virtualbox" do |v|
    v.name = name
    v.customize ["modifyvm", :id, "--memory", 1024]
    v.gui = false
  end

  config.vm.boot_timeout = 300
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.network "private_network", ip: "192.168.56.101"
  config.vm.network :forwarded_port, guest: 80, host: 1144, auto_correct: true
  config.vm.network :forwarded_port, guest: 22, host: 2020, id: "ssh", auto_correct: true
  config.vm.network :forwarded_port, guest: 3389, host: 3390, id: "rdp", auto_correct: true
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
end
